import Vue from 'vue';
import { NavBar, Form, Field, Button, Toast, CountDown, Tabbar, TabbarItem, Icon, Image as VanImage, Grid, GridItem, Cell, CellGroup,Dialog,Tab, Tabs ,List,PullRefresh,Popup,Search,Divider ,Loading ,ImagePreview,Picker ,DatetimePicker    } from 'vant';

Vue.use(NavBar);
Vue.use(Form);
Vue.use(Field);
Vue.use(Button);
Vue.use(Toast);
Vue.use(CountDown);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Icon);
Vue.use(VanImage);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Dialog);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(List);
Vue.use(PullRefresh);
Vue.use(Popup);
Vue.use(Search);
Vue.use(Divider);
Vue.use(ImagePreview);
Vue.use(Loading);
Vue.use(Picker);
Vue.use(DatetimePicker);